# Generated by Django 4.0.3 on 2022-03-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagedb',
            options={'verbose_name': 'Main page', 'verbose_name_plural': 'Main page'},
        ),
    ]
